title: catch-all-favorite
description: 毎週の情報のキャッチアップ情報を管理する
theme: minima
markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings

relative_links:
  enabled: true
  collections: true

optional_front_matter:
  remove_originals: true

titles_from_headings:
  enabled: true
  strip_title: false
  collections: true

defaults:
  - scope:
      path: ""
    values:
      layout: page

include:
  - "フロントエンド情報キャッチアップ"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .github
  - README.md
